<system-data-structure>
    <group identifier="thumbnail" label="Parent Section Page Options" collapsed="true">
        <asset type="file" identifier="image" label="Image for Section Page" help-text="Optional - may be used by Section listings"/>
        <text type="dropdown" identifier="section-icon" label="Icon for Section Page" default="---">
            <dropdown-item value="---"/>
            <dropdown-item value="adjust"/>
            <dropdown-item value="adn"/>
            <dropdown-item value="align-center"/>
            <dropdown-item value="align-justify"/>
            <dropdown-item value="align-left"/>
            <dropdown-item value="align-right"/>
            <dropdown-item value="ambulance"/>
            <dropdown-item value="anchor"/>
            <dropdown-item value="android"/>
            <dropdown-item value="angle-down"/>
            <dropdown-item value="angle-left"/>
            <dropdown-item value="angle-right"/>
            <dropdown-item value="angle-up"/>
            <dropdown-item value="apple"/>
            <dropdown-item value="archive"/>
            <dropdown-item value="arrow-down"/>
            <dropdown-item value="arrow-left"/>
            <dropdown-item value="arrow-right"/>
            <dropdown-item value="arrow-up"/>
            <dropdown-item value="asterisk"/>
            <dropdown-item value="backward"/>
            <dropdown-item value="ban-circle"/>
            <dropdown-item value="bar-chart"/>
            <dropdown-item value="barcode"/>
            <dropdown-item value="beaker"/>
            <dropdown-item value="beer"/>
            <dropdown-item value="bell"/>
            <dropdown-item value="bell-alt"/>
            <dropdown-item value="bitbucket"/>
            <dropdown-item value="bitbucket-sign"/>
            <dropdown-item value="bold"/>
            <dropdown-item value="bolt"/>
            <dropdown-item value="book"/>
            <dropdown-item value="bookmark"/>
            <dropdown-item value="bookmark-empty"/>
            <dropdown-item value="briefcase"/>
            <dropdown-item value="btc"/>
            <dropdown-item value="bug"/>
            <dropdown-item value="building"/>
            <dropdown-item value="bullhorn"/>
            <dropdown-item value="bullseye"/>
            <dropdown-item value="calendar"/>
            <dropdown-item value="calendar-empty"/>
            <dropdown-item value="camera"/>
            <dropdown-item value="camera-retro"/>
            <dropdown-item value="caret-down"/>
            <dropdown-item value="caret-left"/>
            <dropdown-item value="caret-right"/>
            <dropdown-item value="caret-up"/>
            <dropdown-item value="certificate"/>
            <dropdown-item value="check"/>
            <dropdown-item value="check-empty"/>
            <dropdown-item value="check-minus"/>
            <dropdown-item value="check-sign"/>
            <dropdown-item value="chevron-down"/>
            <dropdown-item value="chevron-left"/>
            <dropdown-item value="chevron-right"/>
            <dropdown-item value="chevron-sign-down"/>
            <dropdown-item value="chevron-sign-left"/>
            <dropdown-item value="chevron-sign-right"/>
            <dropdown-item value="chevron-sign-up"/>
            <dropdown-item value="chevron-up"/>
            <dropdown-item value="circle"/>
            <dropdown-item value="circle-arrow-down"/>
            <dropdown-item value="circle-arrow-left"/>
            <dropdown-item value="circle-arrow-right"/>
            <dropdown-item value="circle-arrow-up"/>
            <dropdown-item value="circle-blank"/>
            <dropdown-item value="cloud"/>
            <dropdown-item value="cloud-download"/>
            <dropdown-item value="cloud-upload"/>
            <dropdown-item value="cny"/>
            <dropdown-item value="code"/>
            <dropdown-item value="code-fork"/>
            <dropdown-item value="coffee"/>
            <dropdown-item value="cog"/>
            <dropdown-item value="cogs"/>
            <dropdown-item value="collapse"/>
            <dropdown-item value="collapse-alt"/>
            <dropdown-item value="collapse-top"/>
            <dropdown-item value="columns"/>
            <dropdown-item value="comment"/>
            <dropdown-item value="comment-alt"/>
            <dropdown-item value="comments"/>
            <dropdown-item value="comments-alt"/>
            <dropdown-item value="compass"/>
            <dropdown-item value="copy"/>
            <dropdown-item value="credit-card"/>
            <dropdown-item value="crop"/>
            <dropdown-item value="css3"/>
            <dropdown-item value="cut"/>
            <dropdown-item value="dashboard"/>
            <dropdown-item value="desktop"/>
            <dropdown-item value="double-angle-down"/>
            <dropdown-item value="double-angle-left"/>
            <dropdown-item value="double-angle-right"/>
            <dropdown-item value="double-angle-up"/>
            <dropdown-item value="download"/>
            <dropdown-item value="download-alt"/>
            <dropdown-item value="dribbble"/>
            <dropdown-item value="dropbox"/>
            <dropdown-item value="edit"/>
            <dropdown-item value="edit-sign"/>
            <dropdown-item value="eject"/>
            <dropdown-item value="ellipsis-horizontal"/>
            <dropdown-item value="ellipsis-vertical"/>
            <dropdown-item value="envelope"/>
            <dropdown-item value="envelope-alt"/>
            <dropdown-item value="eraser"/>
            <dropdown-item value="eur"/>
            <dropdown-item value="exchange"/>
            <dropdown-item value="exclamation"/>
            <dropdown-item value="exclamation-sign"/>
            <dropdown-item value="expand"/>
            <dropdown-item value="expand-alt"/>
            <dropdown-item value="external-link"/>
            <dropdown-item value="external-link-sign"/>
            <dropdown-item value="eye-close"/>
            <dropdown-item value="eye-open"/>
            <dropdown-item value="facebook"/>
            <dropdown-item value="facebook-sign"/>
            <dropdown-item value="facetime-video"/>
            <dropdown-item value="fast-backward"/>
            <dropdown-item value="fast-forward"/>
            <dropdown-item value="female"/>
            <dropdown-item value="fighter-jet"/>
            <dropdown-item value="file"/>
            <dropdown-item value="file-alt"/>
            <dropdown-item value="file-text"/>
            <dropdown-item value="file-text-alt"/>
            <dropdown-item value="film"/>
            <dropdown-item value="filter"/>
            <dropdown-item value="fire"/>
            <dropdown-item value="fire-extinguisher"/>
            <dropdown-item value="flag"/>
            <dropdown-item value="flag-alt"/>
            <dropdown-item value="flag-checkered"/>
            <dropdown-item value="flickr"/>
            <dropdown-item value="folder-close"/>
            <dropdown-item value="folder-close-alt"/>
            <dropdown-item value="folder-open"/>
            <dropdown-item value="folder-open-alt"/>
            <dropdown-item value="font"/>
            <dropdown-item value="food"/>
            <dropdown-item value="forward"/>
            <dropdown-item value="foursquare"/>
            <dropdown-item value="frown"/>
            <dropdown-item value="fullscreen"/>
            <dropdown-item value="gamepad"/>
            <dropdown-item value="gbp"/>
            <dropdown-item value="gift"/>
            <dropdown-item value="github"/>
            <dropdown-item value="github-alt"/>
            <dropdown-item value="github-sign"/>
            <dropdown-item value="gittip"/>
            <dropdown-item value="glass"/>
            <dropdown-item value="globe"/>
            <dropdown-item value="google-plus"/>
            <dropdown-item value="google-plus-sign"/>
            <dropdown-item value="group"/>
            <dropdown-item value="h-sign"/>
            <dropdown-item value="hand-down"/>
            <dropdown-item value="hand-left"/>
            <dropdown-item value="hand-right"/>
            <dropdown-item value="hand-up"/>
            <dropdown-item value="hdd"/>
            <dropdown-item value="headphones"/>
            <dropdown-item value="heart"/>
            <dropdown-item value="heart-empty"/>
            <dropdown-item value="home"/>
            <dropdown-item value="hospital"/>
            <dropdown-item value="html5"/>
            <dropdown-item value="inbox"/>
            <dropdown-item value="indent-left"/>
            <dropdown-item value="indent-right"/>
            <dropdown-item value="info"/>
            <dropdown-item value="info-sign"/>
            <dropdown-item value="inr"/>
            <dropdown-item value="instagram"/>
            <dropdown-item value="italic"/>
            <dropdown-item value="jpy"/>
            <dropdown-item value="key"/>
            <dropdown-item value="keyboard"/>
            <dropdown-item value="krw"/>
            <dropdown-item value="laptop"/>
            <dropdown-item value="leaf"/>
            <dropdown-item value="legal"/>
            <dropdown-item value="lemon"/>
            <dropdown-item value="level-down"/>
            <dropdown-item value="level-up"/>
            <dropdown-item value="lightbulb"/>
            <dropdown-item value="link"/>
            <dropdown-item value="linkedin"/>
            <dropdown-item value="linkedin-sign"/>
            <dropdown-item value="linux"/>
            <dropdown-item value="list"/>
            <dropdown-item value="list-alt"/>
            <dropdown-item value="list-ol"/>
            <dropdown-item value="list-ul"/>
            <dropdown-item value="location-arrow"/>
            <dropdown-item value="lock"/>
            <dropdown-item value="long-arrow-down"/>
            <dropdown-item value="long-arrow-left"/>
            <dropdown-item value="long-arrow-right"/>
            <dropdown-item value="long-arrow-up"/>
            <dropdown-item value="magic"/>
            <dropdown-item value="magnet"/>
            <dropdown-item value="mail-reply-all"/>
            <dropdown-item value="male"/>
            <dropdown-item value="map-marker"/>
            <dropdown-item value="maxcdn"/>
            <dropdown-item value="medkit"/>
            <dropdown-item value="meh"/>
            <dropdown-item value="microphone"/>
            <dropdown-item value="microphone-off"/>
            <dropdown-item value="minus"/>
            <dropdown-item value="minus-sign"/>
            <dropdown-item value="minus-sign-alt"/>
            <dropdown-item value="mobile-phone"/>
            <dropdown-item value="money"/>
            <dropdown-item value="moon"/>
            <dropdown-item value="move"/>
            <dropdown-item value="music"/>
            <dropdown-item value="off"/>
            <dropdown-item value="ok"/>
            <dropdown-item value="ok-circle"/>
            <dropdown-item value="ok-sign"/>
            <dropdown-item value="paper-clip"/>
            <dropdown-item value="paste"/>
            <dropdown-item value="pause"/>
            <dropdown-item value="pencil"/>
            <dropdown-item value="phone"/>
            <dropdown-item value="phone-sign"/>
            <dropdown-item value="picture"/>
            <dropdown-item value="pinterest"/>
            <dropdown-item value="pinterest-sign"/>
            <dropdown-item value="plane"/>
            <dropdown-item value="play"/>
            <dropdown-item value="play-circle"/>
            <dropdown-item value="play-sign"/>
            <dropdown-item value="plus"/>
            <dropdown-item value="plus-sign"/>
            <dropdown-item value="plus-sign-alt"/>
            <dropdown-item value="print"/>
            <dropdown-item value="pushpin"/>
            <dropdown-item value="puzzle-piece"/>
            <dropdown-item value="qrcode"/>
            <dropdown-item value="question"/>
            <dropdown-item value="question-sign"/>
            <dropdown-item value="quote-left"/>
            <dropdown-item value="quote-right"/>
            <dropdown-item value="random"/>
            <dropdown-item value="refresh"/>
            <dropdown-item value="remove"/>
            <dropdown-item value="remove-circle"/>
            <dropdown-item value="remove-sign"/>
            <dropdown-item value="renren"/>
            <dropdown-item value="reorder"/>
            <dropdown-item value="repeat"/>
            <dropdown-item value="reply"/>
            <dropdown-item value="reply-all"/>
            <dropdown-item value="resize-full"/>
            <dropdown-item value="resize-horizontal"/>
            <dropdown-item value="resize-small"/>
            <dropdown-item value="resize-vertical"/>
            <dropdown-item value="retweet"/>
            <dropdown-item value="road"/>
            <dropdown-item value="rocket"/>
            <dropdown-item value="rss"/>
            <dropdown-item value="rss-sign"/>
            <dropdown-item value="save"/>
            <dropdown-item value="screenshot"/>
            <dropdown-item value="search"/>
            <dropdown-item value="share"/>
            <dropdown-item value="share-alt"/>
            <dropdown-item value="share-sign"/>
            <dropdown-item value="shield"/>
            <dropdown-item value="shopping-cart"/>
            <dropdown-item value="sign-blank"/>
            <dropdown-item value="signal"/>
            <dropdown-item value="signin"/>
            <dropdown-item value="signout"/>
            <dropdown-item value="sitemap"/>
            <dropdown-item value="skype"/>
            <dropdown-item value="smile"/>
            <dropdown-item value="sort"/>
            <dropdown-item value="sort-by-alphabet"/>
            <dropdown-item value="sort-by-alphabet-alt"/>
            <dropdown-item value="sort-by-attributes"/>
            <dropdown-item value="sort-by-attributes-alt"/>
            <dropdown-item value="sort-by-order"/>
            <dropdown-item value="sort-by-order-alt"/>
            <dropdown-item value="sort-down"/>
            <dropdown-item value="sort-up"/>
            <dropdown-item value="spinner"/>
            <dropdown-item value="stackexchange"/>
            <dropdown-item value="star"/>
            <dropdown-item value="star-empty"/>
            <dropdown-item value="star-half"/>
            <dropdown-item value="star-half-empty"/>
            <dropdown-item value="step-backward"/>
            <dropdown-item value="step-forward"/>
            <dropdown-item value="stethoscope"/>
            <dropdown-item value="stop"/>
            <dropdown-item value="strikethrough"/>
            <dropdown-item value="subscript"/>
            <dropdown-item value="suitcase"/>
            <dropdown-item value="sun"/>
            <dropdown-item value="superscript"/>
            <dropdown-item value="table"/>
            <dropdown-item value="tablet"/>
            <dropdown-item value="tag"/>
            <dropdown-item value="tags"/>
            <dropdown-item value="tasks"/>
            <dropdown-item value="terminal"/>
            <dropdown-item value="text-height"/>
            <dropdown-item value="text-width"/>
            <dropdown-item value="th"/>
            <dropdown-item value="th-large"/>
            <dropdown-item value="th-list"/>
            <dropdown-item value="thumbs-down"/>
            <dropdown-item value="thumbs-down-alt"/>
            <dropdown-item value="thumbs-up"/>
            <dropdown-item value="thumbs-up-alt"/>
            <dropdown-item value="ticket"/>
            <dropdown-item value="time"/>
            <dropdown-item value="tint"/>
            <dropdown-item value="trash"/>
            <dropdown-item value="trello"/>
            <dropdown-item value="trophy"/>
            <dropdown-item value="truck"/>
            <dropdown-item value="tumblr"/>
            <dropdown-item value="tumblr-sign"/>
            <dropdown-item value="twitter"/>
            <dropdown-item value="twitter-sign"/>
            <dropdown-item value="umbrella"/>
            <dropdown-item value="underline"/>
            <dropdown-item value="undo"/>
            <dropdown-item value="unlink"/>
            <dropdown-item value="unlock"/>
            <dropdown-item value="unlock-alt"/>
            <dropdown-item value="upload"/>
            <dropdown-item value="upload-alt"/>
            <dropdown-item value="usd"/>
            <dropdown-item value="user"/>
            <dropdown-item value="user-md"/>
            <dropdown-item value="vk"/>
            <dropdown-item value="volume-down"/>
            <dropdown-item value="volume-off"/>
            <dropdown-item value="volume-up"/>
            <dropdown-item value="warning-sign"/>
            <dropdown-item value="weibo"/>
            <dropdown-item value="windows"/>
            <dropdown-item value="wrench"/>
            <dropdown-item value="xing"/>
            <dropdown-item value="xing-sign"/>
            <dropdown-item value="youtube"/>
            <dropdown-item value="youtube-play"/>
            <dropdown-item value="youtube-sign"/>
            <dropdown-item value="zoom-in"/>
            <dropdown-item value="zoom-out"/>
        </text>
        <text wysiwyg="true" identifier="summary" label="Summary for Section Page" wysiwyg-toolbar-remove="font formatting,insert image,insert table,"/>
    </group>
    <group identifier="main-content" label="Main Content Options">
        <text type="radiobutton" identifier="title-alignment" label="Title / Summary Alignment" default="Default (Vertical)" help-text="How the title text and summary text relate to each other">
            <radio-item value="Default (Vertical)"/>
            <radio-item value="Horizontal Sections"/>
        </text>
        <text type="dropdown" identifier="layout" label="Layout" default="Full Width + Links" required="true">
            <dropdown-item value="Full Width + Links" show-fields="main-content/unlink-headers"/>
            <dropdown-item value="Full Width + Tiles"/>
            <dropdown-item value="Full Width + No Subpages"/>
            <dropdown-item value="Tiles + No Subpages"/>
            <dropdown-item value="Featured Tiles + No Subpages"/>
            <dropdown-item value="Tiled Summaries"/>
            <dropdown-item value="Magazine Archive"/>
        </text>
        <text type="checkbox" identifier="unlink-headers" label="Unlink Headers?">
            <checkbox-item value="Yes"/>
        </text>
        <text identifier="button-text" label="Button Text (for Thumbnail Lists)"/>
        <group identifier="selected-links" label="Tiled Summaries Options" restrict-to-groups="OIT WDG Central Managers" collapsed="true">
            <asset type="page" identifier="link" label="Page Link to include with Summary" multiple="true" render-content-depth="1"/>
        </group>
    </group>
    <group identifier="side" label="Sidebar" collapsed="true">
        <group identifier="item" label="Sidebar Item" multiple="true">
            <!-- feature -->
            <!-- <text identifier="heading" label="Heading" help-text="Optional - for Callouts or Flexible Entry"/>-->
            <text type="dropdown" identifier="type2" label="Type of Content" default="Select an option" help-text="Select which option you will display">
                <dropdown-item value="Select an option"/>
                <dropdown-item value="Callouts"/>
                <dropdown-item value="Calendar - Trumba"/>
                <dropdown-item value="Content Box"/>
                <dropdown-item value="Hours"/>
                <dropdown-item value="News Center Widget"/>
                <dropdown-item value="Profile"/>
                <dropdown-item value="Related Links"/>
                <dropdown-item value="Social Media Icons"/>
                <dropdown-item value="Testimonial"/>
            </text>
            <text type="radiobutton" identifier="item-priority" label="Placement" default="Add to existing site-wide set" help-text="Page settings relative to Site-wide settings">
                <radio-item value="Add to existing site-wide set"/>
                <radio-item value="Replace site-wide set"/>
                <radio-item value="Do not display this type on this page"/>
            </text>
            <asset type="block" identifier="block" label="Select a Component Block" render-content-depth="3" help-text="for Feature, Quick Links, News, Calendar, Audience Nav, Quick Links"/>
            <asset type="page" identifier="callout-page" label="-OR- Select Callout Page" multiple="true" render-content-depth="2" help-text="Select one or more callouts"/>
        </group>
    </group>
</system-data-structure>
